### ISSUE TITLE
Please check other plugins

### ISSUE THREAD

**Issue by pcav** [lequynhhoa/Check-Defined-Convert-CRS#1]
There are some other plugins doing apparently similar tasks, e.g.
http://plugins.qgis.org/plugins/searchEpsgCRS/
http://plugins.qgis.org/plugins/Coordtransform/
As reducing the number of plugins with overlapping functionality is a current aim, to reduce confusion among users and to promote cooperation among developers, I'd be grateful if you could check others and see if there is scope for merging. Adding to the About details about differences would also be appreciated.
Thanks.

**Comment by lequynhhoa** [comment]
Thank you. I checked it, it is not overlapping with other plugin. In the past, I had check coordinate system and convert system. Now, I make a function defined coordinate system (Only used to VietNam). And I make a multiple menu for that.

So do I remove the plugin "convert coordinate system VN2000"? And I will keep "Check coordinate system" plugin, because someone (not vietnamese) no need using 2 functions "Defined coordinate system". They can install single plugin one.

This plugin have 3 functions: check, defined and convert coordinate system.

The first check coordinate, normally you must chose to "Properties" and go to metadata to check coordinate system. And once time, you must open and view a layer. With this plugin, you can check faster coordinate system all layer. They will print all information of layers. Especially, with Vietnam local coordinate system VN2000, this tool will print the name which the user often remember.

The second, for defined coordinate system, it's used to Vietnam Forest Map (VN2000 Noibo), it helps to defined CRS overlay with google map, satellite image, because VN2000 Noibo used 3 parameters so they don't overlay with GE.

Finally, convert coordinate system use to convert between coordinates, especially convert VN2000 noi bo (Vietnam) to WGS84 Latlong, UTM overlay with Google earth.

**Comment by pcav** [comment]
Thanks a lot for the detailed explanation. Perhaps some of this could go in the About?
